
WS       [ \t]*
DIGIT    [0-9]
NATURAL  {DIGIT}+
INTEGER  [-]?{NATURAL}
DECIMAL  {INTEGER}(.{NATURAL})?
DPARM    {DECIMAL}
IPARM    {INTEGER}
SPEC     [ds]{WS}\n
TRIPLE   {INTEGER}{WS},{WS}{INTEGER}{WS},{WS}{INTEGER}{WS}\n
POSITION {TRIPLE}
VECTOR   {TRIPLE}
COLOR    {TRIPLE}
EMISS    {TRIPLE}
RADIUS   {DPARM}{WS}\n
FOV      {IPARM}{WS}\n
POBJ     p{WS}\n
SOBJ     s{WS}\n
COBJ     c{WS}\n
ROBJ     r{WS}\n
QOBJ     q{WS}\n
PCMD     {POBJ}{SPEC}{VECTOR}{POSITION}{COLOR}{EMISS}
SCMD     {SOBJ}{SPEC}{RADIUS}{POSTION}{COLOR}{EMISS}
CCMD     {COBJ}{POSITION}{VECTOR}{FOV}
RCMD     {ROBJ}
QCMD     {QOBJ}
CMD      {PCMD}|{SCMD}|{CCMD}|{RCMD}|{QCMD}

%%

CMD { x = 3; }

%%
